language: php

php:
  - 5.6

before_script:
  - composer install --dev
  
script: vendor/bin/simple-phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
